name: Sync TFS to GitHub

on:
  workflow_dispatch:

jobs:
 build:
  runs-on: windows-latest
  steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - name: run Poweshell script
        run: |
         pwsh ./.github/workflows/SynADOtoGitHub.ps1
        shell: pwsh 
