name: Sync TFS to GitHub

on:
  workflow_dispatch:

jobs:
 build:
  runs-on: windows-latest
  steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - name: run Poweshell script
        run: |
              ./.github/workflows/SynADOtoGitHub.ps1 -DESTINATIONPAT ${{ secrets.DESTINATIONPAT }} -SOURCEPAT ${{ secrets.SOURCEPAT }}
        shell: pwsh
        
      - name: run another Powershell Script 
        uses: actions/checkout@v3
      - name: run Poweshell script  
        run: |
              ./.github/workflows/Sync_23.1.ps1 -DESTINATIONPAT ${{ secrets.DESTINATIONPAT }} -SOURCEPAT ${{ secrets.TFSPAT }}
        shell: pwsh      
