name: Sync TFS to GitHub

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TFS repository
        uses: actions/checkout@v2
        with:
          repository: yangalwar@dev.azure.com/yangalwar/ProjectFromGit/_git/ProjectFromGit
          token: ${{ secrets.SOURCEPAT }}

      - name: Push to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DESTINATIONPAT }}
          branch: main  # Change this to your target branch
