name: Sync TFS to GitHub

on:
  workflow_dispatch:

jobs:
 build:
  runs-on: windows-latest
  steps:
   - name: Checkout repository
     uses: actions/checkout@v2
   # - name: run Poweshell script
   #   run: |
   #    pwsh 
